# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14319ff8782265a6f94ef0b788795ea7d36096a2fbe5c0ef2faeee2a1d05c764b69d59d7fb53f894aad2cdcdd46986f3897d8ae765cf139f2b7fe885a9a95af5

test:
  secret_key_base: 9b5293aa72d4a2cf99562ffa2feefb2873bf7a5a6b77fcec4f7df470b287d477343c13529dc9c56d5ce1387c48e76c31f5667979fb8925363af6cbbdf767b5c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
